### ISSUE TITLE
[Az docs] update azure module docs help url https://docs.* to https://learn.*

### ISSUE THREAD

**Issue by LucasYao93** [FL-LearningGroup/LucasNote#39]
## Tasks
- [ ] Summary count of the module files that content match https://docs.*.
- [ ] Use script to replace on main branch
- [ ] Replace file on generation branch
