### ISSUE TITLE
[Daily]2022-11-02

### ISSUE THREAD

**Issue by LucasYao93** [FL-LearningGroup/LucasNote#42]
# Task

- [x] add workspace api json for ApplicationInsights
- [x] azure module shift left
- [ ] DMS - Dress Create page

**Comment by LucasYao93** [comment]
# Summary
 DMS - Dress Create page, 参考服装小程序，重新设计dress model.
