### ISSUE TITLE
[Daily]2022-11-03

### ISSUE THREAD

**Issue by LucasYao93** [FL-LearningGroup/LucasNote#44]
# Task
- [x] 1. Generate cmdlet design markdown for Workbook of the  ApplicationInsights.
- [ ] 2. Generate cmdlet design markdown of the ImportExport.
- [ ] 3. Design dress module.
