### ISSUE TITLE
[Daily]2022-11-15

### ISSUE THREAD

**Issue by LucasYao93** [FL-LearningGroup/LucasNote#50]
# Task
- [x] generation docs help url
- [x]  compare autorest.powershell sdk 
- [x] SchoolManagementSystem: Function design,Model design.
