### ISSUE TITLE
[Daily]2022-11-21

### ISSUE THREAD

**Issue by LucasYao93** [FL-LearningGroup/LucasNote#54]
# Tasks
- [x] Workbook to main branch
- [x] Autorest.powershell sdk compare script PR
- [ ] Init TSM project
