### ISSUE TITLE
[Daily]2022-12-07

### ISSUE THREAD

**Issue by LucasYao93** [FL-LearningGroup/LucasNote#59]
# Task

- [ ] VoiceServices examples and test cases
- [ ] Parse cmdlet doc markdown
- [ ] SchoolMaster Student module
